### ISSUE TITLE
Null values in Foundation floors data.

### ISSUE THREAD

**Issue by sleepycat** [cds-snc/nrcan_api#315]
For some reason the foundation floors have null values in them.

```
 mongoexport --quiet -d energuide -c dwellings -q '{evaluations: {$elemMatch: {"evaluationType": "E"}}}' | jq 'del(.. | ._id?)'
...lots of output....
          "floors": [
            {
              "floorTypeEnglish": "Slab",
              "floorTypeFrench": "Dalle",
              "insulationNominalRsi": null,
              "insulationNominalR": null,
              "insulationEffectiveRsi": null,
              "insulationEffectiveR": null,
              "areaMetres": 72.6432,
              "areaFeet": 781.9249472263218,
              "perimeterMetres": 34.7466,
              "perimeterFeet": 113.998035144,
              "widthMetres": null,
              "widthFeet": null,
              "lengthMetres": null,
              "lengthFeet": null
            }
          ],
```

@buckley-w-david Any thoughts on this?

**Comment by buckley-w-david** [comment]
This is expected.
```
 <Floor>
    <Construction isBelowFrostline=""true"" hasIntegralFooting=""false"" heatedFloor=""false"">
        <FloorsAbove idref=""Code 8"" rValue=""0.6894"" nominalInsulation=""0"">4231000660</FloorsAbove>
    </Construction>
    <Measurements isRectangular=""false"" area=""72.6432"" perimeter=""34.7466"" />
</Floor>
```
Here's the xml that that floor came from. Couple of things to notice.
1.  No `width` or `length` since it's not rectangular (Measurements attrbiute `isRectangular` == "false")
2. For the insulation we get the values from the nodes under the Construction node. You'll notice that this is a `Slab` floor, not a `Floor above crawl space`, so of the nodes under Construction we'd be pulling from is called `AddedToSlab`. You'll notice that no such node is present. In the case that it is not present, the behavior in report generator is to just put 'N/A' (Which as we've talked about before is misleading, as it is applicable just not present in this case.) in the box for insulation, but importantly still generates the row.

So looks like it's behaving how I'd expect it to.
